---
title: "Stat 479 Final Project"
author: "Evan O'Keefe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(sf)
```

```{r}
geo_url = "https://data.cityofnewyork.us/api/geospatial/d3c5-ddgc?method=export&format=GeoJSON"

city_sf <- read_sf(geo_url, as_tibble = TRUE) %>% 
  st_transform(2263) %>% 
  select(objectid, zone, borough)

manhattan_sf <- city_sf %>% 
  filter(borough == "Manhattan")

zones <- c("Battery Park City",
           "Central Harlem North",
           "East Harlem North",
           "Hudson Sq",
           "Inwood",
           "Inwood Hill Park",
           "Marble Hill",
           "Meatpacking/West Village West",
           "Union Sq",
           "West Village")

p <- manhattan_sf %>% 
  filter(zone %in% zones) %>% 
  ggplot() +
    geom_sf(data = manhattan_sf, fill = "white") +
    geom_sf(aes(fill = zone)) +
    theme_void() +
    theme(legend.position = "None")

ggsave('hood_map.png', p, bg='transparent')
```


```{r}
all_data <- read_csv("data/pu_data.csv")

df <- all_data %>% 
  group_by(objectid) %>% 
  summarise_at(vars(trip_distance:count), sum)

rides_sf <- manhattan_sf %>% 
  merge(df)

ggplot(rides_sf) +
  geom_sf(data = manhattan_sf, fill = "white") +
  geom_sf(aes(fill = tip_amount / total_amount * 100)) +
  scale_fill_distiller(name = "", direction = 1, palette='Greens') +
  theme_void()
```

```{r}
library(gganimate)
library(transformr)

rides <- read_csv("data/pu_data.csv") %>%
  mutate(date = paste(year, month, sep = "-")) %>% 
  group_by(objectid, date) %>% 
  summarise_at(vars(trip_distance:count), sum)

rides_sf <- manhattan_sf %>% 
  merge(rides)

anim <- ggplot(rides_sf, aes(group=seq_along(date))) +
  geom_sf(data = manhattan_sf, fill = "white") +
  geom_sf(aes(fill = total_amount / 1e6)) +
  scale_fill_distiller(
    name='Million $',
    # breaks = c(0, 2.5, 5, 7.5, 10, 12.5, 15),
    direction = 1,
    palette='Greens',
    guide = guide_colorbar(frame.colour = "black", barwidth = 2, barheight = 30)
    ) +
  theme_void(base_size = 30) +
  theme(plot.title = element_text(face = "bold")) +
  labs(
    title = 'Manhattan Yellow Taxi Revenue By Month',
    subtitle = '{closest_state}'
    ) +
  transition_states(month) 

animate(anim, nframes = 60, fps = 5)
anim_save("income.gif")
```

